# Generated by Django 3.2.23 on 2024-04-09 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_mute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='https://ibbea.fcen.uba.ar/wp-content/uploads/2015/06/Pessoa_Neutra23.png', help_text='Введите ссылку на фото', max_length=200, verbose_name='Фото профиля')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии профилей',
            },
        ),
    ]
