# Generated by Django 3.2.23 on 2024-04-28 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата получения звания'),
            preserve_default=False,
        ),
    ]
